config/routes.rb
Rails.application.routes.draw do
  devise_for :users
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    #back end
  namespace :admin do
    resources :products
  end

  #front end
  resources :products
  root 'products#index'

  resources :welcome
  root 'welcome#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
    mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def admin?
      is_admin
  end
  
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
    layout 'admin'
    before_action :authenticate_user!
    before_action :admin_required

    def index
        @products = Product.all
    end

    def new
        @product = Product.new
    end

    def edit
        @product = Product.find(params[:id])
    end

    def create
        @product = Product.new(product_params)

        if @product.save
          flash[:notice] = "新书保存"
          redirect_to admin_products_path
        else
          flash[:warning] = "skdfa"
          render :new
        end
    end

    def update
        @product = Product.find(params[:id])

        if @product.update(product_params)
          flash[:notice] = "编辑成功"
          redirect_to admin_products_path
        else
          flash[:warning] = "skdfa"
          render :edit
        end
    end

    def destroy
        @product = Product.find(params[:id])

        @product.destroy

        flash[:alert] = "已删除 #{@product.title}"
        redirect_to admin_products_path
    end
    private
        def product_params
            params.require(:product).permit(:title, :description, :author, :quantity, :price, :image)
        end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def admin_required
      if !current_user.admin?
          redirect_to "/", flash[:alert] = "不要随便来看人家的后台的啦!"
      end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

    def index
      # TODO: 隐藏
        @products = Product.all
    end

    def show
        @product = Product.find(params[:id])
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def index
      flash[:notice] = "welcome to yikeshu"
    end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { notice: "success", alert: "danger", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flash
    flash.to_hash.slice "notice", "alert", "warning"
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/products/edit.html.erb
<h2>编辑商品</h2>

<%= simple_form_for [:admin, @product] do |f| %>

    <div class="group">
      <%= f.input :title %>
    </div>

    <div class="group">
      <%= f.input :author %>
    </div>

    <div class="group">
      <%= f.input :description %>
    </div>

    <div class="group">
      <%= f.input :quantity %>
    </div>

    <div class="group">
      <%= f.input :price %>
    </div>

    <% if @product.image.present? %>
        <span>现在的图片 </span>
        <%= image_tag @product.image.thumb.url, class: "thumbnail" %>
    <% end %>

    <div class="group">
      <%= f.input :image, as: :file %>
    </div>

    <%= f.submit "Submit", data: { disable_with: "Submiting..."} %>
<% end %>

app/views/admin/products/index.html.erb
<div class="padding-bottom: 20px;">
    <%= link_to "新增商品", new_admin_product_path, class: "btn btn-primary pull-right"  %>
</div>

<table class="table table-bordered">
    <thead>
        <tr>
          <th colspan="2">商品资讯</th>
          <th>作者</th>
          <th width="300">简介</th>
          <th>数量</th>
          <th>价格</th>
          <th>操作选项</th>
        </tr>
    </thead>
    <tbody>
      <% @products.each do |p| %>
        <tr>
          <td>
            <%= link_to p do %>
                  <% if p.image.present? %>
                      <%= image_tag p.image.thumb.url, class: "thumbnail" %>
                  <% else %>
                      <%= image_tag "http://placehold.it/200x200&text=No Pic", class: "thumbnail" %>
                  <% end %>
            <% end %>
          </td>
          <td><%= link_to p.title, p %></td>
          <td><%= p.author %></td>
          <td><%= p.description %></td>
          <td><%= p.quantity %></td>
          <td><%= p.price %></td>
          <td>
            <%= link_to "edit", edit_admin_product_path(p) %>
            <%= link_to admin_product_path(p), method: :delete do %>
                  <i class="fa fa-trash" style="color: red"></i>
            <% end %>

          </td>
        </tr>
      <% end %>
    </tbody>
</table>

app/views/admin/products/new.html.erb
<h2>新建商品</h2>

<%= simple_form_for [:admin, @product] do |f| %>

    <div class="group">
      <%= f.input :title %>
    </div>

    <div class="group">
      <%= f.input :author %>
    </div>

    <div class="group">
      <%= f.input :description %>
    </div>

    <div class="group">
      <%= f.input :quantity %>
    </div>

    <div class="group">
      <%= f.input :price %>
    </div>

    <div class="group">
      <%= f.input :image, as: :file %>
    </div>

    <%= f.submit "Submit", data: { disable_with: "Submiting..."} %>
<% end %>

app/views/common/_flashes.html.erb
<% if flash.any? %>
    <% user_facing_flash.each do |key, value| %>
        <div class="alert alert-<%= flash_class(key) %>">
            <button type="button" name="button" class="close" data-dismiss="alert">x</button>
            <%= value %>
        </div>
    <% end %>
<% end %>

app/views/common/_footer.html.erb
<footer class="text-center" style="margin-top: 20px;">
  <%# TODO:  固定 %>
  <p>Copyright ©2017 echobook
    <br>Designed by echoyang
  </p>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="navbar-header">
      <a href="/" class="navbar-brand">EchoBook</a>
  </div>
  <div class="collapse navbar-collapse">
    <ul class="nav navbar-nav">

    </ul>
    <ul class="nav navbar-nav navbar-right">
        <% if !current_user %>
          <li><%= link_to "注册", new_user_registration_path %></li>
          <li><%= link_to content_tag(:i, "登入", class: "fa fa-sign-in"), new_user_session_path %></li>
        <% else %>
          <li class="dropdown">
              <a href="#" class="toggle" data-toggle="dropdown">
                Hi!, <%= current_user.email %>
                <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <% if current_user.admin? %>
                    <li><%= link_to "admin panel", admin_products_path %></li>
                    <br>
                <% end %>
                <li><%= link_to content_tag(:i, "登出", class: "fa fa-sign-out"), destroy_user_session_path, method: :delete %></li>
              </ul>
          </li>
        <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Echobook</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
        <%= render "common/navbar" %>
        <%= render "common/flashes" %>
        <%= yield %>
    </div>
    
    <%= render "common/footer" %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Echobook</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
        <%= render "common/navbar" %>
        <%= render "common/flashes" %>
        <%= yield %>
    </div>
    
    <%= render "common/footer" %>
  </body>
</html>

app/views/products/index.html.erb
<h1>yikeshu</h1>

<div class="row">
  <% @products.each do |p| %>
    <div class="col-md-3 col-xs-6">
      <%= link_to p do %>
                <% if p.image.present? %>
                      <%= image_tag p.image.thumb.url, class: "thumbnail" %>
                <% else %>
                      <%= image_tag "http://placehold.it/200x200&text=No Pic", class: "thumbnail" %>
                <% end %>
      <% end %>
      <%= p.title %> $ <%= p.price %>
    </div>
  <% end %>
</div>

app/views/products/show.html.erb
<h2>ECho 干活</h2>

<div class="row">
    <div class="col-md-6">
      <% if @product.image.present? %>
            <%= image_tag @product.image.medium.url, class: "thumbnail" %>
      <% else %>
            <%= image_tag "http://placehold.it/400x400&text=No Pic", class: "thumbnail" %>
      <% end %>
    </div>

    <div class="col-md-6">

      <h2><%= @product.title %></h2>

      <div class="product-author">
        作者  <%= @product.author %>
      </div>

      <br>

      <div class="product-description" style="height: 100px;">
        简介  <%= @product.description %>
      </div>

      <div class="product-price">
        价格 $  <%= @product.price  %>
      </div>

      <div class="pull-right">
          <%= link_to "添加到购物车", "#", class: "btn btn-lg btn-danger" %>
      </div>
    </div>
</div>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Theme Company</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

</head>
<body>
<style>
.jumbotron {
    background-color: #f4511e; /* Orange */
    color: #ffffff;
}
</style>
<div class="jumbotron">
  <h1>Calling X</h1>
  <p>Tell me, what is it you plan to do with your one wild and precious life?
  探索这个世界没有关系，变得filarious（fun+hilarious）也没有关系。</p>
  <p class="lead"><a class="btn btn-lg btn-warning" href="/jobs">Get Started</a></p>
</div>

</body>
</html>
<style>
.bg-grey {
    background-color: #f6f6f6;
}
</style>

<!-- Container (Services Section) -->
<div class="container-fluid text-center">
  <h2>SERVICES</h2>
  <h4>What we offer</h4>
  <br>
  <div class="row">
    <div class="col-sm-4">
      <span class="glyphicon glyphicon-off logo-small"></span>
      <h4>POWER</h4>
      <p>Take this to find your inner power.</p>
    </div>
    <div class="col-sm-4">
      <span class="glyphicon glyphicon-heart logo-small"></span>
      <h4>LOVE</h4>
      <p>Find Your Love.</p>
    </div>
    <div class="col-sm-4">
      <span class="glyphicon glyphicon-lock logo-small"></span>
      <h4>JOB DONE</h4>
      <p>Get the Job Done and Done Well.</p>
    </div>
  </div>
  <br><br>
  <div class="row">
    <div class="col-sm-4">
      <span class="glyphicon glyphicon-leaf logo-small"></span>
      <h4>GREEN</h4>
      <p>Help to improve the environment.</p>
    </div>
    <div class="col-sm-4">
      <span class="glyphicon glyphicon-certificate logo-small"></span>
      <h4>CERTIFIED</h4>
      <p>Becoming a certified professional.</p>
    </div>
    <div class="col-sm-4">
      <span class="glyphicon glyphicon-wrench logo-small"></span>
      <h4 style="color:#303030;">HARD WORK</h4>
      <p>Work hard and you can achieve anything.</p>
    </div>
  </div>
</div>

<div class="container-fluid text-center bg-grey">
  <h2>Portfolio</h2>
  <h4>What we have created</h4>
  <div class="row text-center">
    <div class="col-sm-4">
      <div class="thumbnail">
        <img src="https://ww3.sinaimg.cn/large/006tKfTcgy1fc0kp71xwsj30b408ct98.jpg" alt="Paris">
        <p><strong>Paris</strong></p>
        <p>Yes, we built Paris</p>
      </div>
    </div>
    <div class="col-sm-4">
      <div class="thumbnail">
        <img src="https://ww2.sinaimg.cn/large/006y8lVajw1fc0kpz0gdtj30b408ct9c.jpg" alt="New York">
        <p><strong>New York</strong></p>
        <p>We built New York</p>
      </div>
    </div>
    <div class="col-sm-4">
      <div class="thumbnail">
        <img src="https://ww2.sinaimg.cn/large/006y8lVajw1fc0kqirojlj30b408cmxb.jpg" alt="San Francisco">
        <p><strong>San Francisco</strong></p>
        <p>Yes, San Fran is ours</p>
      </div>
    </div>
</div>

<h2>What our customers say</h2>
<div id="myCarousel" class="carousel slide text-center" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
    <h4>"CallingX is the best."<br><span style="font-style:normal;">Michael Roe, Vice President, Comment Box</span></h4>
    </div>
    <div class="item">
      <h4>"One word... WOW!!"<br><span style="font-style:normal;">John Doe, Salesman, Rep Inc</span></h4>
    </div>
    <div class="item">
      <h4>"Could I... BE any more happy with this website?"<br><span style="font-style:normal;">Chandler Bing, Actor, FriendsAlot</span></h4>
    </div>
  </div>

  <!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<div class="container-fluid bg-grey">
  <h2 class="text-center">CONTACT</h2>
  <div class="row">
    <div class="col-sm-5">
      <p>Contact us and we'll get back to you within 24 hours.</p>
      <p><span class="glyphicon glyphicon-map-marker"></span> Beijing, China</p>
      <p><span class="glyphicon glyphicon-phone"></span> +00 1515151515</p>
      <p><span class="glyphicon glyphicon-envelope"></span> hr@callingx.com</p>
    </div>
    <div class="col-sm-7">
      <div class="row">
        <div class="col-sm-6 form-group">
          <input class="form-control" id="name" name="name" placeholder="Name" type="text" required>
        </div>
        <div class="col-sm-6 form-group">
          <input class="form-control" id="email" name="email" placeholder="Email" type="email" required>
        </div>
      </div>
      <textarea class="form-control" id="comments" name="comments" placeholder="Comment" rows="5"></textarea><br>
      <div class="row">
        <div class="col-sm-12 form-group">
          <button class="btn btn-default pull-right" type="submit">Send</button>
        </div>
      </div>
    </div>
  </div>
</div>